export const ButtonVariants = {
  primary: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 'l',
    height: 54,
    justifyContent: 'center',
    borderRadius: 30,
    backgroundColor: 'primaryButton',
    alignSelf: 'stretch',
  },
  secondary: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 'l',
    height: 54,
    justifyContent: 'center',
    borderRadius: 30,
    backgroundColor: 'white',
    alignSelf: 'stretch',
  },
  outline: {
    flexDirection: 'row',
    paddingHorizontal: 'l',
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'primary',
    alignSelf: 'stretch',
  },
};
