import {Platform} from 'react-native';

export const TextVariants = {
  defaults: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'left',
  },
  description: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 18,
    lineHeight: 27,
    textAlign: 'left',
  },
  title: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '500',
    textAlign: 'left',
  },
  h1: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Black',
    fontSize: 40,
    lineHeight: 48,
    letterSpacing: 0,
    textAlign: 'left',
  },
  h2: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 21,
    lineHeight: 27,
  },
  h3: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0,
    textAlign: 'left',
  },
  h4: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 22,
    lineHeight: 37,
    letterSpacing: 0,
  },
  heading: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '500',
    textAlign: 'left',
  },
  subheading: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 20,
    lineHeight: 30,
    fontWeight: '500',
    textAlign: 'left',
  },
  subHeader: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'left',
  },
  button: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.04,
  },
  link: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    textDecorationLine: 'underline',
    fontWeight: '500',
    textAlign: 'left',
  },
  body: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 24,
    textAlign: 'left',
  },
  bold: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Bold',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
  },
  extraBold: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-ExtraBold',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: Platform.OS === 'ios' ? '700' : '600',
  },
  button_primary: {
    color: 'white',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '700',
    letterSpacing: 0.04,
    textTransform: 'uppercase',
  },
  button_secondary: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '700',
    letterSpacing: 0.04,
    textTransform: 'uppercase',
  },
  button_outline: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '700',
    letterSpacing: 0.04,
    textTransform: 'uppercase',
  },
  thin: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Light',
    fontSize: 14,
    lineHeight: 27,
    fontWeight: '400',
  },
  subtitle: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 24,
    fontWeight: '400',
  },
  caption: {
    color: 'blackPrimary',
    fontFamily: 'Poppins-Regular',
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
  },
};
