import {
  DarkGray,
  LightGray,
  White,
  Black,
  Red,
  BackgroundWhite,
  BackgroundHeader,
  TernaryBackground,
  Sky,
  SkyLight,
  NightShade,
  NightShadeLight,
  WarmGray,
  ShimmerDarkGreyColor,
  ShimmerLightGreyColor,
  LightBlue,
  ShadowStartColor,
  ShadowEndColor,
  Gray,
  Gray2,
  NeutralGray,
  Border,
  BorderOpacity,
  BorderOpacityDark,
  DarkBorderOpacityLight,
  BorderInputLight,
  Placeholder,
  GoldOrange,
  Sand,
  Silver,
  Divider,
  GrayBorder,
  Green,
  Red2,
  GoldOrangeWithOpacity,
  Red3,
  GoldOrangeLight,
  GoldOrangeDark,
  GoldOrangeWithOpacityLight,
  GreenOpacity,
  LightSand,
  Orange,
  BorderLightOpacity,
  Gray3,
  RedWithOpacity,
} from './palette';

export const LightTheme = {
  // background
  primaryBackground: BackgroundWhite,
  cardBackground: White,
  secondaryBackground: BackgroundHeader,
  ternaryBackground: TernaryBackground,

  // brand colors
  primary: DarkGray,
  secondary: Sky,
  secondaryLight: SkyLight,
  ternary: NightShade,
  ternaryLight: NightShadeLight,

  // nuteral
  blackPrimary: Black,
  darkGray: DarkGray,
  lightGray: LightGray,
  warmGray: WarmGray,
  danger: Red,
  white: White,
  lightBlue: LightBlue,
  blue: LightBlue,
  neutralGray: NeutralGray,
  silver: Silver,
  divider: Divider,

  //shimmer effect
  shimmerDark: ShimmerDarkGreyColor,
  shimmerLight: ShimmerLightGreyColor,

  // shadow colors
  shadowStartColor: ShadowStartColor,
  shadowEndColor: ShadowEndColor,

  // Actual colors
  gray: Gray,
  gray2: Gray2,
  gray4: LightGray,
  border: Border,
  borderOpacity: BorderOpacity,
  borderOpacityDark: BorderOpacityDark,
  darkBorderOpacityLight: DarkBorderOpacityLight,
  borderInput: BorderInputLight,
  placeholder: Placeholder,
  primaryButton: GoldOrange,
  primaryButtonOpacity: Sand,
  primaryButtonLight: GoldOrangeWithOpacity,
  inputGray: GrayBorder,
  green: Green,
  greenOpacity: GreenOpacity,
  red2: Red2,
  red3: Red3,
  redWithOpacity: RedWithOpacity,
  alwaysWhite: White,
  alwaysBlack: DarkGray,
  darkGrey: BorderOpacityDark,
  borderLightOpacity: BorderLightOpacity,

  goldOrangeLight: GoldOrangeLight,
  goldOrangeDark: GoldOrangeDark,
  goldOrangeWithOpacityLight: GoldOrangeWithOpacityLight,
  orange: Orange,

  lightSand: LightSand,

  transparent: 'transparent',
  gray3: Gray3,
};
